show databases;
use customer_behaviour;
show tables;
select * from customers;
-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount_usd) AS revenue
FROM customers
group by gender;
-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount_usd
FROM customers
WHERE discount_applied = 'Yes'
AND purchase_amount_usd >= (SELECT AVG(purchase_amount_usd) FROM customers);
-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased,
ROUND(AVG(review_rating),2) AS "Average Product Rating"
FROM customers
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;
-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type,
ROUND(AVG(purchase_amount_usd),2)
FROM customers
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type;
-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, 
       COUNT(customer_id) AS total_customers, 
       ROUND(AVG(purchase_amount_usd), 2) AS avg_spend, 
       ROUND(SUM(purchase_amount_usd), 2) AS total_revenue
FROM customers
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;
-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customers
)

SELECT 
    customer_segment,
    COUNT(*) AS Number_of_Customers
FROM customer_type
GROUP BY customer_segment;
-- Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category, 
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) DESC) as item_rank
from customers
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status;
-- Q10. What is the revenue contribution of each age group?
SELECT 
CASE
    WHEN age < 20 THEN 'Teen'
    WHEN age BETWEEN 20 AND 35 THEN 'Young Adult'
    WHEN age BETWEEN 36 AND 50 THEN 'Adult'
    ELSE 'Senior'
END AS age_group,

SUM(purchase_amount_usd) AS total_revenue

FROM customers
GROUP BY age_group
ORDER BY total_revenue DESC;


